Fiap.Web.Donation1/Controllers/HomeController.cs
using Fiap.Web.Donation1.Data;
using Fiap.Web.Donation1.Models;
using Fiap.Web.Donation1.Repository;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Transactions;

namespace Fiap.Web.Donation1.Controllers
{
    public class HomeController : BaseController
    {
        private readonly ILogger<HomeController> _logger;

        private readonly ProdutoRepository produtoRepository;

        public HomeController(
            ILogger<HomeController> logger, 
            DataContext dataContext, 
            IHttpContextAccessor httpContextAccessor) : base(httpContextAccessor)
        {
            _logger = logger;
            produtoRepository = new ProdutoRepository(dataContext);
        }

        [HttpGet]
        public IActionResult Index()
        {
            var lista = produtoRepository.FindAllDisponivelParaTroca(true, UsuarioId);

            return View(lista);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Fiap.Web.Donation1/Controllers/TrocaController.cs
using Fiap.Web.Donation1.Data;
using Fiap.Web.Donation1.Migrations;
using Fiap.Web.Donation1.Repository;
using Fiap.Web.Donation1.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Fiap.Web.Donation1.Controllers
{
    public class TrocaController : BaseController
    {
        private readonly ProdutoRepository produtoRepository;

        private readonly TrocaRepository trocaRepository;

        private readonly TrocaService trocaService;

        public TrocaController(DataContext dataContext, 
                               IHttpContextAccessor httpContextAccessor) : base (httpContextAccessor) 
        {
            produtoRepository = new ProdutoRepository(dataContext);
            trocaRepository = new TrocaRepository(dataContext);
            trocaService = new TrocaService(produtoRepository, trocaRepository);
        }



        [HttpGet]
        public IActionResult Index(int id)
        {
            var trocaModel = new Models.TrocaModel();
            trocaModel.ProdutoId1 = id;
            trocaModel.ProdutoModel1 = produtoRepository.FindById(id);

            ComboMeusProdutos();

            return View(trocaModel);
        }


        [HttpPost]
        public IActionResult Index(Models.TrocaModel trocaModel)
        {

            try
            {
                trocaService.TrocarProdutos(trocaModel);

                TempData["Mensagem"] = "Troca registrada com sucesso.";
            }
            catch (Exception ex)
            {
                TempData["Erro"] = ex.Message;
            }

            return RedirectToAction("Index", "Home");
        }

        



        private void ComboMeusProdutos()
        {
            var produtos = produtoRepository.FindAllDisponivelDoUsuario(true, UsuarioId);

            var comboProdutos = new SelectList(produtos, "ProdutoId", "Nome" );

            ViewBag.MeusProdutos = comboProdutos;

        }

    }
}

Fiap.Web.Donation1/Views/Home/Index.cshtml
@model IList<ProdutoModel>

@{
    int? UsuarioId = Context.Session.GetInt32("UsuarioId");
}

<div class="text-center">
    <h1 class="display-4">Vitrine</h1>
    <hr />

    @if (!String.IsNullOrEmpty((String)@TempData["Mensagem"]))
    {
        <div class="alert alert-warning" role="alert">@TempData["Mensagem"]</div>
    }

    @if (!String.IsNullOrEmpty((String)@TempData["Erro"]))
    {
        <div class="alert alert-danger" role="alert">@TempData["Erro"]</div>
    }

    <div class="d-flex flex-wrap">
        @foreach( var produto in Model)
        {
            <div class="card" style="width: 18rem;">
              <div class="card-body">
                    <h5 class="card-title">@produto.Nome</h5>
                <p class="card-text">@produto.Descricao</p>
                <p class="card-text">@produto.Valor</p>

                    @if( UsuarioId == null || UsuarioId == 0 )
                    {
                        <a href="#" class="btn btn-secondary">Trocar</a>
                    } else
                    {
                        <a asp-controller="Troca" asp-action="Index" asp-route-id="@produto.ProdutoId" class="btn btn-primary">Trocar</a>
                    }

              </div>
            </div>
        }
    </div>
</div>