Fiap.Web.Donation1/Controllers/LoginController.cs
using Fiap.Web.Donation1.Models;
using Fiap.Web.Donation1.Repository;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Fiap.Web.Donation1.Controllers
{
    public class LoginController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            IProdutoRepository produtoRepository = new ProdutoRepository(null);

            return View(new UsuarioModel());
        }


        [HttpPost]
        public IActionResult Index(UsuarioModel usuarioModel)
        {
            UsuarioModel usuarioRetorno = null;

            #region acessar-repositorio-usuario
            if (usuarioModel.Nome.Equals("Flavio") && usuarioModel.Email.Equals("fmoreni@gmail.com") ) {
                usuarioRetorno = new UsuarioModel()
                {
                    UsuarioId = 1,
                    Nome = "Flavio",
                    Email = "fmoreni@gmail.com"
                };
            }

            if (usuarioModel.Nome.Equals("Eduardo") && usuarioModel.Email.Equals("emoreni@gmail.com"))
            {
                usuarioRetorno = new UsuarioModel()
                {
                    UsuarioId = 2,
                    Nome = "Eduardo",
                    Email = "emoreni@gmail.com"
                };
            }
            #endregion

            // Se encontrou o usuario seguir os processos de login
            #region controlando-fluxo-login


            if ( usuarioRetorno != null)
            {
                var usuarioJson = JsonConvert.SerializeObject(usuarioRetorno);
                HttpContext.Session.SetString("UsuarioLogado", usuarioJson);

                HttpContext.Session.SetInt32("UsuarioId", usuarioRetorno.UsuarioId);
                HttpContext.Session.SetString("UsuarioNome", usuarioRetorno.Nome);

                return RedirectToAction("Index", "Home");
            } else
            {
                ViewBag.Mensagem = "Login incorreto";
                return View(usuarioModel);
            }
            #endregion

        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();

            return RedirectToAction("Index", "Home");
        }
    }
}

Fiap.Web.Donation1/Controllers/ProdutoController.cs
using Fiap.Web.Donation1.Data;
using Fiap.Web.Donation1.Models;
using Fiap.Web.Donation1.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Fiap.Web.Donation1.Controllers
{
    public class ProdutoController : BaseController
    {

        private readonly TipoProdutoRepository tipoProdutoRepository;

        private readonly IProdutoRepository produtoRepository;

        public ProdutoController(DataContext dataContext, 
                                IProdutoRepository prodRepository,  
                                IHttpContextAccessor httpContextAccessor) : base(httpContextAccessor)
        {
            produtoRepository = prodRepository;
            tipoProdutoRepository = new TipoProdutoRepository(dataContext);
        }


        [HttpGet]
        public IActionResult Index() //Lista todos os produtos
        {
            var produtos = produtoRepository.FindAllWithTipoOrderByName();

            return View(produtos);
        }


        
        [HttpGet]
        public IActionResult Novo()
        {
            return View(new ProdutoModel());
        }

        [HttpPost]
        public IActionResult Novo(ProdutoModel produtoModel) {

            if (string.IsNullOrEmpty(produtoModel.Nome))
            {
                ViewBag.Mensagem = "O campo nome é requerido";
                return View(produtoModel);
            }
            else
            {
                produtoModel.UsuarioId = UsuarioId;
                produtoRepository.Insert(produtoModel);

                TempData["Mensagem"] = $"{produtoModel.Nome} cadastrado com sucesso";
                return RedirectToAction("Index");
            }
        }


        [HttpGet]
        public IActionResult Editar(int id)
        {
            ComboTipoProduto();

            var produtoModel = produtoRepository.FindById(id);
            return View(produtoModel);
        }


        [HttpPost]
        public IActionResult Editar(ProdutoModel produtoModel)
        {
            if ( string.IsNullOrEmpty(produtoModel.Nome) )
            {
                ComboTipoProduto();

                ViewBag.Mensagem = "O campo nome é requerido";
                return View(produtoModel);

            } else
            {
                produtoModel.UsuarioId = UsuarioId;
                produtoRepository.Update(produtoModel);

                TempData["Mensagem"] = $"{produtoModel.Nome} alterado com sucesso";

                return RedirectToAction("Index");
            }
        }



        private void ComboTipoProduto()
        {
            var tiposProdutos = tipoProdutoRepository.FindAll();

            var comboTipoProdutos = new SelectList(tiposProdutos, "TipoProdutoId", "Nome");

            ViewBag.TipoProdutos = comboTipoProdutos;
        }
        

    }
}

Fiap.Web.Donation1/Controllers/TipoProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Fiap.Web.Donation1.Data;
using Fiap.Web.Donation1.Models;

namespace Fiap.Web.Donation1.Controllers
{
    public class TipoProdutoController : BaseController
    {
        private readonly DataContext _context;

        public TipoProdutoController(DataContext context, IHttpContextAccessor httpContextAccessor) : base(httpContextAccessor)
        {
            _context = context;
        }

        // GET: TipoProduto
        public async Task<IActionResult> Index()
        {
              return _context.TipoProdutos != null ? 
                          View(await _context.TipoProdutos.ToListAsync()) :
                          Problem("Entity set 'DataContext.TipoProdutos'  is null.");
        }

        // GET: TipoProduto/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TipoProdutos == null)
            {
                return NotFound();
            }

            var tipoProdutoModel = await _context.TipoProdutos
                .FirstOrDefaultAsync(m => m.TipoProdutoId == id);
            if (tipoProdutoModel == null)
            {
                return NotFound();
            }

            return View(tipoProdutoModel);
        }

        // GET: TipoProduto/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TipoProduto/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TipoProdutoId,Nome,Descricao")] TipoProdutoModel tipoProdutoModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tipoProdutoModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tipoProdutoModel);
        }

        // GET: TipoProduto/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TipoProdutos == null)
            {
                return NotFound();
            }

            var tipoProdutoModel = await _context.TipoProdutos.FindAsync(id);
            if (tipoProdutoModel == null)
            {
                return NotFound();
            }
            return View(tipoProdutoModel);
        }

        // POST: TipoProduto/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TipoProdutoId,Nome,Descricao")] TipoProdutoModel tipoProdutoModel)
        {
            if (id != tipoProdutoModel.TipoProdutoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tipoProdutoModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TipoProdutoModelExists(tipoProdutoModel.TipoProdutoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tipoProdutoModel);
        }

        // GET: TipoProduto/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TipoProdutos == null)
            {
                return NotFound();
            }

            var tipoProdutoModel = await _context.TipoProdutos
                .FirstOrDefaultAsync(m => m.TipoProdutoId == id);
            if (tipoProdutoModel == null)
            {
                return NotFound();
            }

            return View(tipoProdutoModel);
        }

        // POST: TipoProduto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TipoProdutos == null)
            {
                return Problem("Entity set 'DataContext.TipoProdutos'  is null.");
            }
            var tipoProdutoModel = await _context.TipoProdutos.FindAsync(id);
            if (tipoProdutoModel != null)
            {
                _context.TipoProdutos.Remove(tipoProdutoModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TipoProdutoModelExists(int id)
        {
          return (_context.TipoProdutos?.Any(e => e.TipoProdutoId == id)).GetValueOrDefault();
        }
    }
}

Fiap.Web.Donation1/Views/Shared/_Layout.cshtml
@{
    int? UsuarioId = 0;
    UsuarioId = Context.Session.GetInt32("UsuarioId");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fiap.Web.Donation1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Fiap.Web.Donation1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Fiap.Web.Donation1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produto</a>
                        </li>

                        @if (UsuarioId != null && UsuarioId != 0)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="TipoProduto" asp-action="Index">Tipo Produto</a>
                            </li>
                        }

                        @if( UsuarioId == null || UsuarioId == 0 ) {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                            </li>
                        }

                        @if (UsuarioId != null && UsuarioId != 0)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">

            @RenderBody()

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Fiap.Web.Donation1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>            
            @RenderSection("Footer", required: false)
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Fiap.Web.Donation1/Views/Shared/_LayoutNoturno.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fiap.Web.Donation1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Fiap.Web.Donation1.styles.css" asp-append-version="true" />
</head>
<body style="background: grey">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Fiap.Web.Donation1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Fiap.Web.Donation1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>